$(function(){
		$('#modalButton').click(function(){	
				$('#modal').modal('show')
					.find('#modalContent')
					.load($(this).attr('value'));
		});
	});
$(function(){
		$('#modala').click(function(){	
				$('#modala').modal('show')
					.find('#modalContentido')
					.load($(this).attr('value'));
		});
	});